### ISSUE TITLE
Update link to now-decommissioned mailing list

### ISSUE THREAD

**Issue by brainwane** [pypa/ssl#11]
https://github.com/pypa/ssl/blob/a0158a1256f5944f84878ae8971ee398e213bd78/setup.py#L146

Per https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ
the pypa-dev Google Group is now decommissioned. Please point to distutils-sig instead.

**Comment by jezdez** [comment]
Good point! I don't have access to the repo anymore though.

**Comment by di** [comment]
@jezdez Added you. But maybe this repo should be archived instead?

**Comment by jezdez** [comment]
@di Yeah, I think that would be best TBH, but I don't feel comfortable making this call as I *read notes* haven't worked on this library since 2013 😬
