### ISSUE TITLE
ValueError: This extension should not be used with Python 2.6 or later (already built in), and has not been tested with Python 2.3.4 or earlier.

### ISSUE THREAD

**Issue by Namita26** [pypa/ssl#5]
I am trying to install ssl by doing `pip install -U ssl`.  But its not installing giving the 

>  ValueError: This extension should not be used with Python 2.6 or later (already built in), and has not been tested with Python 2.3.4 or earlier.
My Python version is 2.7.6

**Comment by Bundas** [comment]
I have the exactly same problem. how did you resolve it?

**Comment by shbnsndr** [comment]
Hi, I am also having the same problem, how to resolve this issue?

**Comment by sigmavirus24** [comment]
I'm sorry. What is the bug here @Namita26? Why is there confusion around this error message?

**Comment by Namita26** [comment]
Closing this issue. The error message is appropriate.

**Comment by sigmavirus24** [comment]
Correct @Namita26. @shbnsndr @Bundas if you're on Python 2.7 you do **not** need this module which is why it refuses to install.
